void menu();
void new_acc();
void edit();
void transact();
void see();
void erase();
static void deposit_money(int);
static void withdraw_money(int);
static void edit_user_data(int);
static void choose_op(int, int);
